# Generated by Django 5.0.6 on 2024-06-27 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_modeloprueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='modeloprueba',
        ),
    ]
